[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "tailwindcsscli -i tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css"]

[serve]
address = "127.0.0.1"
port = 8080

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:8000/"